<a href="https://colab.research.google.com/github/JinLeeGG/AI_Project_Preparation/blob/main/3.%20Data%20Analysis/01.%20Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 넘파이(Numpy)**
넘파이(Numpy)는 파이썬에서 사용되는 과학 및 수학 연산을 위한 강력한 라이브러리입니다. 주로 다차원 배열을 다루는 데에 특화되어 있어, 데이터 분석, 머신러닝, 과학 계산 등 다양한 분야에서 널리 사용됩니다. 넘파이 배열은 C 언어로 구현되어 있어 연산이 빠르고 효율적입니다. 특히 큰 데이터셋에서 수치 연산을 수행할 때 뛰어난 성능을 보입니다. 또한 메모리 사용을 최적화하고 효율적으로 관리합니다.

In [1]:
!pip install numpy

In [2]:
import numpy as np

# **2. 넘파이의 주요 특징과 기능**

### 1. 다차원 배열(N-dimensional array)

넘파이의 핵심은 다차원 배열인 ndarray입니다. ndarray는 동일한 자료형을 가지는 원소들로 이루어져 있습니다. 다차원 배열은 1차원, 2차원, 3차원 등 다양한 차원을 가질 수 있습니다.

In [8]:
list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))
print(type(list1[0]))
print(list1[0]) # indexing 할때는 scalar 값이 나온다.
print(list1[:1]) # slicing 일때는 차원이 유지된다.

list2 = [[1,2,3,4], [5,6,7,8]]
print(list2)
print(type(list2))
print(type(list2[0]))

[1, 2, 3, 4]
<class 'list'>
<class 'int'>
1
[1]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'list'>


In [12]:
ndarr1 = np.array([1,2,3,4])
print(ndarr1)
print(type(ndarr1))
print(ndarr1[0])
print(type(ndarr1[0]))
# 리스트와 NDarray의 변환은 언제든지 가능하다.

[1 2 3 4]
<class 'numpy.ndarray'>
1
<class 'numpy.int64'>


### 2. 리스트와 ndarray 변환

데이터 타입을 다른 데이터 타입으로 변환할 수 있습니다. 리스트에서 배열로의 변환은 np.array() 함수를 사용하고, 배열에서 리스트로의 변환은 tolist() 메서드를 사용합니다.

In [16]:
# 리스트를 ndarray로 변환
list1 = [1, 2, 3, 4]
ndarr1 = np.array(list1)
print(ndarr1)
print(type(ndarr1))

# ndarray를 리스트로 변환
list2 = ndarr1.tolist()
print(list2)
print(type(list2))

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


### 3. ndarray의 데이터 타입

넘파이의 ndarray는 동일한 자료형을 가지는 원소들로 이루어져 있으며, 다양한 데이터 타입을 지원합니다.

In [21]:
list1 = [1, 3.14, "python", "◆", True]
print(list1)
print(type(list1))
print(type(list1[0]))
print(type(list1[1]))
print(type(list1[2]))
print(type(list1[3]))
print(type(list1[4]))

[1, 3.14, 'python', '◆', True]
<class 'list'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>


In [23]:
ndarr1 = np.array([1,2,3,4])
print(ndarr1)
print(type(ndarr1))
print(type(ndarr1[0]))
print(type(ndarr1[1]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [26]:
ndarr2 = np.array([1,2,3.14,4])
print(ndarr2) # float로 변환된다.
print(type(ndarr2[0]))
print(type(ndarr2[1]))

[1.   2.   3.14 4.  ]
<class 'numpy.float64'>
<class 'numpy.float64'>


In [27]:
# 우선순위 float > int > bool
ndarr3 = np.array([1, 2, 3.14, True]) # True는 1.0 으로 전환된다. True : 1 , False: 0
print(ndarr3)
print(type(ndarr3))
print(type(ndarr3[0]))
print(type(ndarr3[1]))
print(type(ndarr3[2]))
print(type(ndarr3[3]))

[1.   2.   3.14 1.  ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [29]:
# 우선순위 String > float > int > bool
ndarr4 = np.array(['1', 2, 3.14, True])
print(ndarr4)
print(type(ndarr4))
print(type(ndarr4[0]))
print(type(ndarr4[1]))
print(type(ndarr4[2]))
print(type(ndarr4[3]))

['1' '2' '3.14' 'True']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [30]:
ndarr3 = np.array([1, 2, 3.14, True], dtype=int) # int 로 전체변환
print(ndarr3)
print(type(ndarr3))
print(type(ndarr3[0]))
print(type(ndarr3[1]))
print(type(ndarr3[2]))
print(type(ndarr3[3]))

[1 2 3 1]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [31]:
ndarr4 = np.array(['1', 2, 3.14, True], dtype=int) # string 이여도 int로 전체변환
print(ndarr4)
print(type(ndarr4))
print(type(ndarr4[0]))
print(type(ndarr4[1]))
print(type(ndarr4[2]))
print(type(ndarr4[3]))

[1 2 3 1]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
